# Scene: room0,
# bound_min: [-3.8696494102478027, -2.347562551498413, -1.4041465520858765]
# bound_max: [3.869352102279663, 2.348031520843506, 1.3950726985931396]

base_config: ../trainer.yaml
exp_name: test-octree-resolution-10-6-0.2
data:
    dataset_args:
        data_path: "data/newercollege-lidar-rotated"
        min_depth: 0.6
        max_depth: 25.0
        # offset: [20, 29, 14]
model:
    octree_cfg:
        resolution: 0.2
        tree_depth: 10 # 0.2*512=102.4m
        semi_sparse_depth: 6
        init_voxel_num: 2000000
        insertion_threshold: 3
        skip_insertion_if_exists: true # speed up a bit
        # gradient_augmentation: true
key_frame_set:
    insert_ratio: 0.5
    selection_window_size: 16