# Scene: room0,
# bound_min: [-3.8696494102478027, -2.347562551498413, -1.4041465520858765]
# bound_max: [3.869352102279663, 2.348031520843506, 1.3950726985931396]

base_config: ../trainer.yaml
exp_name: noise-filter-0.1
data:
    dataset_args:
        data_path: "data/newercollege-lidar-rotated"
        min_depth: 0.6
        max_depth: 40.0
        noise_filter_threshold: 0.1
        min_blob_size: 30
        # offset: [20, 29, 14]
    start_frame: 0
    end_frame: -1
model:
    only_prior: false
    octree_cfg:
        resolution: 0.7
        tree_depth: 8 # 0.7*256=179.2m
        semi_sparse_depth: 4
        init_voxel_num: 50000
        insertion_threshold: 1
        skip_insertion_if_exists: true # speed up a bit
        # gradient_augmentation: true
sample_table:
    identifier: grad_sdf.sample_table.SampleTableConfig
    pts_per_voxel: 500
    surface_voxel_num: 50000
    device: cuda
    frames_num: 1988
    extra_ratio: 0.0
criterion:
    reconstruction_loss_threshold: 1.0
    perturbation_loss_threshold: 5.0
    eikonal_loss_surface_threshold: 5.0
    eikonal_loss_space_threshold: 5.0
    projection_loss_threshold: 5.0
