# Scene: room0,
# bound_min: [-3.8696494102478027, -2.347562551498413, -1.4041465520858765]
# bound_max: [3.869352102279663, 2.348031520843506, 1.3950726985931396]

base_config: ../trainer.yaml
exp_name: test-octree-resolution-8-5-0.7
data:
    dataset_args:
        data_path: "data/newercollege-lidar-rotated"
        min_depth: 0.6
        max_depth: 40.0
        # offset: [20, 29, 14]
model:
    octree_cfg:
        resolution: 0.7
        tree_depth: 8 # 0.7*256=179.2m
        semi_sparse_depth: 4
        init_voxel_num: 50000
        insertion_threshold: 8
        skip_insertion_if_exists: true # speed up a bit
        # gradient_augmentation: true
sample_table:
    identifier: grad_sdf.sample_table.SampleTableConfig
    pts_per_voxel: 200
    surface_voxel_num: 50000
    device: cuda
    frames_num: 1988
